config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations",
    :sessions => "users/sessions"
  }

  root 'pages#home'

  get :pageone, to: 'pages#page1', as: :pageone
  get :pagetwo, to: 'pages#page2', as: :pagetwo
  get :settings, to: 'pages#settings', as: :settings
  patch :settings, to: 'pages#update_settings', as: :update_settings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
  devise :omniauthable, :omniauth_providers => [:twitter]

  validates_presence_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "App"
  end

  def page1
    @title = "Page 1"
  end

  def page2
    @title = "Page 2"
  end

  def settings
    @title = "Settings"
    @user = current_user
  end

  def update_settings
    @user = current_user
    if @user.update_attributes(params[:user].permit(:email))
      redirect_to settings_path
    else
      @title = "Settings"
      render 'settings'
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include Devise::Controllers::Rememberable

  def twitter
    @user = User.create

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
    else
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def new
    @title = "New Account"
    build_resource({})
    respond_with resource
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new
    @title = "Sign In"
    super
  end

  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message! :notice, :signed_out if signed_out
    redirect_to after_sign_out_path_for(resource_name)
  end       
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navigation.erb
<nav class="navbar navbar-light">
  <ul class="nav navbar-nav float-xs-right">
    <% if user_signed_in? %>
      
      <li class="nav-item"><%= link_to 'Settings', settings_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link', remote: true %></li>
    <% else %>
      <li class="nav-item"><%= link_to 'Login', new_user_session_path, class: 'nav-link' %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || "Rails Turbolinks iOS Demo" %></title>
    <%= csrf_meta_tags %>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_form.erb
<%= form_for @user, url: update_settings_path, remote: true do |form| %>
<%# form_tag update_settings_path do %>

  <%= render 'shared/errors', object: form.object %>
  
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>
  
  <%= form.submit 'Save Settings', class: 'btn btn-primary' %>
<% end %>

app/views/pages/home.html.erb
<p>
Welcome to a demo of Rails, Turbolinks, and iOS!
</p>

<ul>
  <li><%= link_to 'Page 1', pageone_path %></li>
  <li><%= link_to 'Page 2', pagetwo_path %></li>
</ul>

app/views/pages/page1.erb
<h2>Page 1 contents</h2>

app/views/pages/page2.erb
<h2>Page 2 contents</h2>

app/views/pages/registration.erb
<div class="content">
  <div class="row">
    <section class="section section-well section-sessions">
      <h2>Sign Up</h2>

      <%= form_for(resource, as: resource_name, url: registration_path(resource_name), remote: true) do |f| %>
        <%= devise_error_messages! %>

        <div class="form-group row">
          <div class="col-md-4">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-md-4">
            <%= f.label :password %>
            <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
          </div>
        </div>
        <label>
          Already have an account?
          <%= link_to 'Login', new_user_session_path %>
        </label>

        <div class="actions"> 
          <%= f.submit "Sign up", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </section>
  </div>
</div>

app/views/pages/settings.erb
<%= render 'form' %>

app/views/pages/settings.js.erb
$("form").html("<%= j render('form') %>");

app/views/shared/_errors.erb
<% if object.errors.any? %>

  <h4><%= pluralize object.errors.count, "error" %></h4>

  <div class="error_explanation">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>